-- ============================================================
-- 002_queue.sql
-- ------------------------------------------------------------
-- Match queue state machine according to PDF Section 6.2.
-- ============================================================

-- Clean up existing type to prevent version conflicts
DROP TYPE IF EXISTS queue_status CASCADE;

CREATE TYPE queue_status AS ENUM ('waiting', 'matched', 'cancelled');


CREATE TABLE IF NOT EXISTS public.queue (
  id              UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  status          queue_status DEFAULT 'waiting',
  
  -- Matching Metadata
  matched_with    UUID REFERENCES public.users(id) ON DELETE SET NULL,
  agora_channel   TEXT, -- UUID generated by the 'claim_match' RPC
  
  -- Filters (from wireframes/Section 5.3)
  language_pref   TEXT DEFAULT 'English',
  
  -- Timestamps
  entered_at      TIMESTAMPTZ DEFAULT now(),
  matched_at      TIMESTAMPTZ,
  
  -- Ensure a user can only have ONE active waiting/matched row
  CONSTRAINT unique_active_user UNIQUE (user_id)
);

-- Index for fast matching on 'waiting' status
CREATE INDEX idx_queue_waiting ON public.queue (status) WHERE status = 'waiting';
